# Generated by Django 6.0.1 on 2026-02-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='name',
            new_name='key',
        ),
    ]
