# Generated by Django 6.0.1 on 2026-02-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Simple (No Variant)'), ('single', 'Single Variant'), ('variant', 'Multi Variant')], default='simple', max_length=20),
        ),
    ]
