# Generated by Django 6.0.1 on 2026-02-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shipping_type', models.CharField(choices=[('STANDARD', 'Standard'), ('EXPRESS', 'Express')], default='STANDARD', max_length=20)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_order_free_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
